#!/bin/sh

sleep 2


for i in `pgrep rcu*` ; do taskset -p 1 $i ; done &>/dev/null 
for i in `pgrep kworker*` ; do taskset -p 1 $i ; done &>/dev/null 
for i in `pgrep ksoftirqd*` ; do taskset -p 1 $i ; done &>/dev/null
for i in `pgrep ktimersoftd*` ; do taskset -p 1 $i ; done &>/dev/null
for i in `pgrep cpu*` ; do taskset -p 1 $i ; done &>/dev/null
for i in `pgrep migration*` ; do taskset -p 1 $i ; done &>/dev/null
for i in `pgrep posix*` ; do taskset -p 1 $i ; done &>/dev/null
for i in `pgrep kworker*` ; do renice 20 -p $i ; done
#for i in `pgrep irq/*` ; do taskset -p 8 $i ; done &>/dev/null
for i in `pstree -p upmpdcli | grep -o [0-9]*` ; do taskset -p 8 $i ; done &>/dev/null

#ehciのaffinity　値は１６進数で設定　1ならcpu0 2ならcpu1 4ならcpu2 8ならcpu3となる。
echo 4 > /proc/irq/10/smp_affinity
#eth0のaffnity
echo 2 > /proc/irq/18/smp_affinity


renice 20 -p $(pidof ntpd)
renice 20 -p $(pidof syslogd)
renice 20 -p $(pidof klogd)

sysctl -p
echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor &>/dev/null

ifup eth1

iptables -t nat -A POSTROUTING -o eth1 -s 10.0.0.2 -j MASQUERADE
